#!/usr/bin/env python3
# Generated by run_simulation_campaign.py. Runs INSIDE the
# session sim_session.py brought up, so every stage sees
# the same /compute_ik and the same scene.
import json, os, subprocess, sys, time
WS = '/home/gausms/kortex_ws'
STAGES = json.loads('[{"key": "teleop_orientation_cost", "title": "What the pinned wrist costs", "group": "teleoperation", "tier": "stack", "argv": ["/usr/bin/python3", "scripts/measure_orientation_cost.py", "--dirs", "14", "--arm", "both", "--seeds", "3"], "produces": ["recordings/baselines/orientation_cost.json"], "timeout": 3600, "note": "mean reach per direction under each orientation policy"}, {"key": "tasks_t1", "title": "T1, both stages, over the whole densified path", "group": "robot tasks", "tier": "stack", "argv": ["/usr/bin/python3", "scripts/verify_t1.py"], "produces": ["recordings/baselines/t1_paths.json"], "timeout": 2400, "note": "N=10 repeats per pose, densified to 20 mm, both arms confirmed at home before any sample"}, {"key": "tasks_msc", "title": "The MSc task set, every coordinate", "group": "robot tasks", "tier": "stack", "argv": ["/usr/bin/python3", "scripts/verify_msc_tasks.py"], "produces": [], "timeout": 3600, "note": "IK success and wearer clearance for every waypoint of T0, T1, T2 and T3"}, {"key": "tasks_dance", "title": "The demonstration routines", "group": "robot tasks", "tier": "stack", "argv": ["/usr/bin/python3", "scripts/verify_dance_paths.py"], "produces": [], "timeout": 2400, "note": "every waypoint of the three routines"}]')
OUT = '/home/gausms/kortex_ws/recordings/simulations/20260831_002055'

recs = []
for i, st in enumerate(STAGES):
    print("[stack %d/%d] %s" % (i + 1, len(STAGES), st["key"]), flush=True)
    t0 = time.time()
    try:
        p = subprocess.run(st["argv"], cwd=WS, capture_output=True,
                           text=True, timeout=st["timeout"])
        out, code = (p.stdout or "") + (p.stderr or ""), p.returncode
    except subprocess.TimeoutExpired:
        out, code = "", -9
    except Exception as exc:
        out, code = str(exc), -1
    rec = dict(st)
    rec["seconds"] = round(time.time() - t0, 1)
    rec["exit"] = code
    rec["status"] = "ok" if code == 0 else "failed"
    rec["tail"] = "\n".join(out.splitlines()[-40:])
    lp = os.path.join(OUT, "logs", st["key"] + ".log")
    os.makedirs(os.path.dirname(lp), exist_ok=True)
    open(lp, "w").write(out)
    rec["log"] = os.path.relpath(lp, WS)
    rec["produces"] = [dict(path=q, exists=os.path.exists(os.path.join(WS, q)))
                       for q in st["produces"]]
    print("    %s in %.1f s" % (rec["status"], rec["seconds"]), flush=True)
    recs.append(rec)
open(os.path.join(OUT, "stack_stages.json"), "w").write(json.dumps(recs, indent=2))
