#!/usr/bin/env python3
"""index_recordings.py -- one readable table of every recorded session.

    python3 scripts/index_recordings.py            # print
    python3 scripts/index_recordings.py --write    # write docs/RECORDINGS.md

WHY THIS EXISTS. A session is a directory of JSON and CSV next to a multi-GB
bag, and the bag is the one part that cannot go anywhere near GitHub. Without
an index the only way to answer "what did we actually capture, and when" is to
open each directory in turn -- and the answer that matters (which channels were
DEAD) is one field inside one file.

WHAT IT REPORTS, and why each column earns its place:
  * duration and rows      -- a session that ran for 4 s is not a trial.
  * channels DEAD          -- the whole point. A recording where the master
                              arm never published looks exactly like one where
                              it did, until you read this.
  * bag size               -- so it is obvious which sessions hold the giant
                              raw-image bags recorded before 2026-08-30, when
                              the recorder still captured uncompressed frames
                              at 1121 MB/s.
  * figures                -- graphs are written on STOP, so their presence is
                              the evidence that a session was stopped cleanly
                              rather than killed.
"""
import argparse
import glob
import json
import os

WS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.join(WS, "recordings", "sessions")


def _load(path):
    try:
        return json.load(open(path))
    except Exception:                                         # noqa: BLE001
        return {}


def sessions():
    out = []
    for d in sorted(glob.glob(os.path.join(ROOT, "*")), reverse=True):
        if not os.path.isdir(d):
            continue
        s = _load(os.path.join(d, "summary.json"))
        m = _load(os.path.join(d, "manifest.json"))
        bag = os.path.join(d, "bag")
        bag_b = 0
        if os.path.isdir(bag):
            bag_b = sum(os.path.getsize(os.path.join(bag, f))
                        for f in os.listdir(bag)
                        if os.path.isfile(os.path.join(bag, f)))
        trail = os.path.join(d, "trail.csv")
        out.append(dict(
            name=os.path.basename(d),
            started=m.get("started") or s.get("session", ""),
            label=m.get("label", ""),
            mode=m.get("mode", ""),
            shared=m.get("shared_autonomy", ""),
            secs=s.get("duration_s"),
            rows=s.get("trail_rows"),
            live=s.get("channels_live") or [],
            dead=s.get("channels_DEAD"),
            events=s.get("n_events"),
            bag_b=bag_b,
            figures=len(glob.glob(os.path.join(d, "figures", "*.png"))),
            trail_kb=(os.path.getsize(trail) / 1024.0
                      if os.path.exists(trail) else 0.0),
        ))
    return out


def table(rows):
    out = []
    out.append("| session | started | duration | rows | channels DEAD | "
               "events | figures | bag |")
    out.append("| --- | --- | ---: | ---: | --- | ---: | ---: | ---: |")
    for r in rows:
        dead = r["dead"]
        if dead is None:
            dead_s = "_not summarised_"
        elif not dead:
            dead_s = "none"
        else:
            dead_s = "**" + ", ".join(dead) + "**"
        out.append("| `%s` | %s | %s | %s | %s | %s | %d | %s |" % (
            r["name"], r["started"] or "—",
            ("%.2f s" % r["secs"]) if r["secs"] is not None else "—",
            r["rows"] if r["rows"] is not None else "—",
            dead_s,
            r["events"] if r["events"] is not None else "—",
            r["figures"],
            ("%.2f GB" % (r["bag_b"] / 1e9)) if r["bag_b"] else "—"))
    return "\n".join(out)


def document(rows):
    done = [r for r in rows if r["secs"] is not None]
    total_bag = sum(r["bag_b"] for r in rows)
    head = [
        "# Recorded sessions",
        "",
        "Generated by `scripts/index_recordings.py`. One row per directory "
        "under `recordings/sessions/`.",
        "",
        "**The bags are NOT in this repository.** They are multi-gigabyte "
        "`.mcap` files, over GitHub's 100 MB per-file limit, and "
        "`recordings/sessions/*/bag/` is gitignored. What IS here is the part "
        "you read: `trail.csv`, `summary.json`, `events.jsonl`, "
        "`manifest.json` and the figures.",
        "",
        "| | |",
        "| --- | --- |",
        "| sessions | %d |" % len(rows),
        "| with a summary (stopped cleanly) | %d |" % len(done),
        "| bags on disk, not in git | %.1f GB |" % (total_bag / 1e9),
        "",
        "**`channels DEAD` is the column that matters.** A recording where the "
        "master arm never published looks identical to one where it did, until "
        "you read that field. `figures` is the other tell: graphs are written "
        "on STOP, so a session with 0 figures was killed rather than stopped.",
        "",
        "## What a session contains",
        "",
        "| file | what is in it |",
        "| --- | --- |",
        "| `trail.csv` | 76 columns at ~19 Hz: sim and real joints (7 per "
        "arm), master pose and quaternion, commanded end-effector, and a "
        "freshness flag per channel |",
        "| `summary.json` | duration, row count, channels live and DEAD, event "
        "counts, bag size |",
        "| `events.jsonl` | one line per event: session start/stop, clutch, "
        "refusals with their reasons |",
        "| `manifest.json` | label, mode, and whether shared autonomy was on — "
        "the condition the run was made under |",
        "| `arms.jsonl` | both real arms read straight off the Kortex API |",
        "| `figures/` | `clutch`, `freshness`, `joints_left`, `joints_right`, "
        "`trails` |",
        "| `bag/` | every ROS topic. **Not in git.** |",
        "",
        "## Sessions",
        "",
    ]
    return "\n".join(head) + table(rows) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    rows = sessions()
    doc = document(rows)
    if a.write:
        out = os.path.join(WS, "docs", "RECORDINGS.md")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        open(out, "w").write(doc)
        print("wrote %s (%d sessions)" % (out, len(rows)))
    else:
        print(doc)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
