#!/usr/bin/env python3
"""TURN A SIMULATION CAMPAIGN INTO THE THESIS'S TABLES AND FIGURES.

    python3 scripts/make_sim_figures.py                       # newest campaign
    python3 scripts/make_sim_figures.py --campaign recordings/simulations/<x>
    python3 scripts/make_sim_figures.py --self-test

WHY THIS EXISTS.  Numbers reached the thesis by being copied out of a
terminal, which means a re-run changes nothing in the document and a document
figure cannot be traced to the run that produced it.  Everything this writes
carries the campaign stamp it was generated from, so a figure in the PDF names
the directory a reader can check it against.

IT REFUSES RATHER THAN INVENTS.  A stage that did not run produces no table.
There is no default, no last-known-good and no placeholder: a missing result
must be visibly missing, because a table of plausible numbers with no run
behind it is the worst artefact this project could produce.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys

WS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(WS, "extras", "thesis", "thesis_v3", "figures", "sim")


#: THE CAMPAIGNS THIS RUN WAS GIVEN. Set by main() and by the self-test.
#: Scoped rather than globbed, so a generator that reads ACROSS campaigns --
#: `orientation_convergence` is the only one -- still refuses when it was
#: handed nothing, which is the property the self-test checks.
CAMPAIGNS = []


class Missing(Exception):
    """A result this figure needs was not produced by the campaign."""


def newest_campaign():
    ds = sorted(glob.glob(os.path.join(WS, "recordings", "simulations", "*")))
    ds = [d for d in ds if os.path.exists(os.path.join(d, "campaign.json"))]
    if not ds:
        raise Missing("no campaign with a campaign.json under "
                      "recordings/simulations")
    return ds[-1]


def load(camp):
    with open(os.path.join(camp, "campaign.json")) as fh:
        run = json.load(fh)
    by = {s["key"]: s for s in run["stages"]}
    return run, by


def load_many(camps):
    """Merge several campaign directories into one view.

    The standalone stages and the ones needing a live `move_group` are run
    separately -- one MoveIt stack for all of the latter, because HARD
    CONSTRAINT 3 forbids two and two verifiers against one `move_group` have
    already produced a measurement where one run's furniture was in the
    other's scene. Merging here is what lets the thesis report them as one
    campaign, which is what they are.

    A later directory WINS on a key it also has, and it wins whatever its
    status: a re-run that failed must not be masked by an older success.
    Each stage remembers the directory it actually came from, so a figure can
    always name the run behind it.
    """
    merged, stamps, homes = {}, [], {}
    for c in camps:
        run, by = load(c)
        stamps.append(run.get("stamp", os.path.basename(c)))
        for k, v in by.items():
            merged[k] = v
            homes[k] = c
    return merged, homes, "+".join(stamps)


def need(by, key):
    st = by.get(key)
    if st is None:
        raise Missing("stage %s is not in this campaign" % key)
    if st.get("status") != "ok":
        raise Missing("stage %s did not succeed (%s)"
                      % (key, st.get("status")))
    return st


def log_of(camp, key):
    if isinstance(camp, dict):                # a homes map from load_many
        camp = camp.get(key, "")
    p = os.path.join(camp, "logs", key + ".log")
    if not os.path.exists(p):
        raise Missing("no log for %s" % key)
    return open(p).read()


def head(stamp, what):
    return ("%% GENERATED by scripts/make_sim_figures.py from simulation\n"
            "%% campaign %s. Do not edit: re-run the campaign instead.\n"
            "%% %s\n" % (stamp, what))


# ====================================================================== CV
def cv_selftest(camp, by, stamp):
    need(by, "cv_arithmetic")
    root = camp.get("cv_arithmetic", "") if isinstance(camp, dict) else camp
    p = glob.glob(os.path.join(root, "cv_selftest", "**", "self_test.json"),
                  recursive=True)
    if not p:
        raise Missing("cv_arithmetic produced no self_test.json")
    checks = json.load(open(p[0]))["checks"]
    rows = []
    for c in checks:
        name = c["check"]
        det = c["detail"]
        control = name.startswith("THE CONTROL") or name.startswith("PLUMBING")
        name = re.sub(r"^THE CONTROL: ", "", name)
        name = re.sub(r"^PLUMBING: ", "", name)
        rows.append((name, det, control, c["passed"]))
    body = []
    for name, det, control, ok in rows:
        if det in ("", "None"):
            det = "---"
        else:
            try:                       # a bare number: give it a sane width
                det = "%.3g" % float(det)
            except ValueError:
                pass                   # it already carries its unit
        body.append("    %s%s & %s & %s \\\\"
                    % ("\\textit{control:} " if control else "",
                       _tex(name), _tex(det), "\\checkmark" if ok else "FAIL"))
    return (head(stamp, "the vision pipeline against a constructed scene")
            + "\\begin{tabular}{@{}p{0.60\\linewidth}rc@{}}\n"
              "  \\toprule\n"
              "  What was checked & Measured & \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


# ================================================================== teleop
_GEN_RE = re.compile(
    r"^\s+(clamp_towards|ruckig|synchronised-clamp)\s+"
    r"([\d.]+)\s+([\d.]+)\s+([\d.]+)x\s+(\S+)\s+(YES|NO)\s*$", re.M)


def teleop_generators(camp, by, stamp):
    need(by, "teleop_motion")
    txt = log_of(camp, "teleop_motion")
    arms = {}
    for arm in ("LEFT", "RIGHT"):
        i = txt.find("%s arm," % arm)
        if i < 0:
            raise Missing("no %s block in the motion log" % arm)
        j = txt.find(" arm,", i + 6)
        arms[arm.lower()] = _GEN_RE.findall(txt[i:j if j > 0 else len(txt)])
    if not arms["left"]:
        raise Missing("the motion log's generator table did not parse")
    label = {"clamp_towards": "per-joint clamp (was)",
             "ruckig": "jerk-limited, phase-sync (now)",
             "synchronised-clamp": "synchronised clamp (fallback)"}
    body = []
    for gen in ("clamp_towards", "ruckig", "synchronised-clamp"):
        cells = []
        for arm in ("left", "right"):
            r = [x for x in arms[arm] if x[0] == gen]
            if not r:
                raise Missing("%s missing for the %s arm" % (gen, arm))
            cells.append(r[0])
        L, R = cells
        body.append(
            "    %s & %s & %s & %s & %s & %s & %s \\\\"
            % (label[gen], L[1], R[1], L[2], R[2], L[3] + "$\\times$",
               "yes" if L[5] == "YES" else "\\textbf{no}"))
    return (head(stamp, "three motion generators on one commanded slew")
            + "\\begin{tabular}{@{}lcccccc@{}}\n"
              "  \\toprule\n"
              "  & \\multicolumn{2}{c}{off-path, max}\n"
              "  & \\multicolumn{2}{c}{same-cycle, max}\n"
              "  & peak $\\dot{q}$ & joints \\\\\n"
              "  \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
              "  Generator & left & right & left & right\n"
              "  & of limit & together \\\\\n"
              "  & \\si{\\milli\\metre} & \\si{\\milli\\metre}\n"
              "  & \\si{\\milli\\metre} & \\si{\\milli\\metre} & & \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


_STEP_RE = re.compile(r"max_step\s+([\d.]+) rad ->\s+(\d+) cycles,\s+([\d.]+) mm")


def teleop_stepsweep(camp, by, stamp):
    """Excursion against step size, with the SHIPPED step marked.

    The point of the figure is the left-hand plateau -- shrinking the step
    does not shrink the excursion -- so the annotation sits on the plateau
    and the shipped value is marked, rather than leaving a reader to work out
    which end of a log axis the delivered system lives at.
    """
    need(by, "teleop_motion")
    pts = _STEP_RE.findall(log_of(camp, "teleop_motion"))
    if len(pts) < 4:
        raise Missing("the step sweep did not parse")
    pts = sorted(((float(s_), float(mm)) for s_, _c, mm in pts))
    shipped = max(p[0] for p in pts)
    coords = " ".join("(%g,%g)" % p for p in pts)
    top = max(p[1] for p in pts)
    return (head(stamp, "the per-joint clamp against its own step size")
            + """\\begin{tikzpicture}
\\begin{axis}[
    width=0.80\\linewidth, height=54mm,
    xmode=log, log basis x=10,
    xmin=0.007, xmax=0.6, ymin=-4, ymax=%.0f,
    xlabel={per-joint step bound $\\Delta$ (\\si{\\radian}), smaller to the left},
    ylabel={off-path excursion (\\si{\\milli\\metre})},
    xlabel style={font=\\scriptsize}, ylabel style={font=\\scriptsize},
    tick label style={font=\\scriptsize},
    axis lines*=left, grid=major, grid style={gray!18},
]
\\addplot[red!65!black, thick, mark=*, mark size=1.5pt] coordinates {%s};
\\addplot[green!45!black, very thick] coordinates {(0.007,0)(0.6,0)};
\\node[font=\\tiny, green!45!black, anchor=south west]
  at (axis cs:0.0075,1.5)
  {jerk-limited, phase-synchronised: \\SI{0.0}{\\milli\\metre} at every step};
\\draw[black!55, dotted, thick]
  (axis cs:%g,-4) -- (axis cs:%g,%.0f);
\\node[font=\\tiny, anchor=north east, black!55, align=right]
  at (axis cs:%g,%.0f) {the shipped\\\\step bound};
\\node[font=\\tiny, red!65!black, anchor=north west, align=left]
  at (axis cs:0.0105,%.0f)
  {the excursion SETTLES here:\\\\a smaller step does not\\\\make it smaller. It is
   the\\\\shape of the algorithm};
\\end{axis}
\\end{tikzpicture}
""" % (top + 22, coords, shipped, shipped, top + 14,
       shipped * 0.92, top + 14, top - 8))


_SMOOTH_RE = re.compile(r"^(none \(raw\)|ema\(0\.3\)\s+\[was\]|one_euro\s+\[now\])\s+"
                        r"([\d.]+)\s+([\d.]+)\s*$", re.M)


def teleop_smoothing(camp, by, stamp):
    need(by, "teleop_smoothing")
    rows = _SMOOTH_RE.findall(log_of(camp, "teleop_smoothing"))
    if len(rows) != 3:
        raise Missing("the smoothing table did not parse (%d rows)" % len(rows))
    label = {"none (raw)": "no filter",
             "ema(0.3)  [was]": "fixed EMA, $\\alpha=\\num{0.3}$ (was)",
             "one_euro  [now]": "1-Euro, speed-adaptive (now)"}
    body = []
    for name, still, lag in rows:
        key = re.sub(r"\s+", "  ", name.strip())
        body.append("    %s & %s & %s \\\\"
                    % (label.get(key, _tex(name)), still, lag))
    return (head(stamp, "master smoothing, through the shipped node")
            + "\\begin{tabular}{@{}lcc@{}}\n"
              "  \\toprule\n"
              "  Control law & stillness & lag \\\\\n"
              "  & \\si{\\milli\\metre} RMS & \\si{\\milli\\metre} \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


def teleop_replay(camp, by, stamp):
    """Stillness and lag on a real operator's hand, per arm."""
    need(by, "teleop_replay")
    root = camp.get("teleop_replay", "") if isinstance(camp, dict) else camp
    p = os.path.join(WS, "recordings", "baselines", "teleop_replay.json")
    if not os.path.exists(p):
        raise Missing("teleop_replay produced no baseline")
    d = json.load(open(p))
    label = {"none (raw)": "no filter",
             "ema(0.3)  [was]": "fixed EMA, $\\alpha=\\num{0.3}$ (was)",
             "one_euro  [now]": "1-Euro, speed-adaptive (now)"}
    arms = d["arms"]
    body = []
    for i, row in enumerate(arms[0]["rows"]):
        cells = []
        for a in arms:
            r = a["rows"][i]
            cells += ["%.2f" % r["still_mm"], "%.2f" % r["lag_mm"]]
        body.append("    %s & %s \\\\"
                    % (label.get(row["law"].strip().replace("  ", "  "),
                                 _tex(row["law"])), " & ".join(cells)))
    hdr = " & ".join("\\multicolumn{2}{c}{%s arm}" % a["arm"] for a in arms)
    sub = " & ".join(["still & lag"] * len(arms))
    n = arms[0]["frames"]
    return (head(stamp, "the smoother over %d recorded frames" % n)
            + "\\begin{tabular}{@{}l%s@{}}\n" % ("cc" * len(arms))
            + "  \\toprule\n  & %s \\\\\n" % hdr
            + "  \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
            + "  Control law & %s \\\\\n" % sub
            + "  & \\si{\\milli\\metre} & \\si{\\milli\\metre}"
              " & \\si{\\milli\\metre} & \\si{\\milli\\metre} \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


# ================================================================ autonomy
def autonomy_sweep(camp, by, stamp):
    need(by, "autonomy_arbitration")
    root = camp.get("autonomy_arbitration", "") if isinstance(camp, dict) else camp
    p = os.path.join(root, "arbitration.json")
    if not os.path.exists(p):
        raise Missing("no arbitration.json")
    d = json.load(open(p))
    ks = sorted(d["rows"], key=lambda x: int(x))
    def series(cond, field):
        return " ".join("(%s,%s)" % (k, d["rows"][k][cond][field]) for k in ks)
    return (head(stamp, "intent inference against a mis-declared table")
            + """\\begin{tikzpicture}
\\begin{axis}[
    width=0.80\\linewidth, height=56mm,
    xmin=0, xmax=125, ymin=-3, ymax=100,
    xlabel={how far the declared object positions are from the real ones (\\si{\\milli\\metre})},
    ylabel={\\%% of %d trials},
    xlabel style={font=\\scriptsize}, ylabel style={font=\\scriptsize},
    tick label style={font=\\scriptsize},
    legend style={font=\\scriptsize, at={(0.5,1.02)}, anchor=south,
                  legend columns=2, draw=none},
    axis lines*=left, grid=major, grid style={gray!18},
]
\\addplot[blue!55!black, thick, mark=square*, mark size=1.4pt] coordinates {%s};
\\addlegendentry{declared: correct}
\\addplot[red!70!black, very thick, mark=triangle*, mark size=1.8pt] coordinates {%s};
\\addlegendentry{declared: confidently WRONG}
\\addplot[green!45!black, thick, mark=*, mark size=1.4pt] coordinates {%s};
\\addlegendentry{measured: correct}
\\addplot[green!45!black, thick, dashed, mark=o, mark size=1.4pt] coordinates {%s};
\\addlegendentry{measured: confidently wrong}
\\draw[gray!60, dotted, thick] (axis cs:60,-3) -- (axis cs:60,100);
\\node[font=\\tiny, anchor=north west, gray!50!black, align=left]
  at (axis cs:62,20) {one cube pitch:\\\\the file points at\\\\the NEIGHBOUR};
\\end{axis}
\\end{tikzpicture}
""" % (d["trials"], series("DECLARED", "correct_pct"),
       series("DECLARED", "wrong_pct"),
       series("CALIBRATED", "correct_pct"),
       series("CALIBRATED", "wrong_pct")))


def autonomy_instructions(camp, by, stamp):
    need(by, "autonomy_instructions")
    root = camp.get("autonomy_instructions", "") if isinstance(camp, dict) else camp
    p = os.path.join(root, "instructions.json")
    if not os.path.exists(p):
        raise Missing("no instructions.json")
    d = json.load(open(p))
    now, before = d["totals"], d["before"]["totals"]
    n = sum(now.values())
    order = ["CORRECT", "ASKED", "REFUSED", "MISUNDERSTOOD"]
    b = " ".join("(%d,%d)" % (i, before[k]) for i, k in enumerate(order))
    a = " ".join("(%d,%d)" % (i, now[k]) for i, k in enumerate(order))
    return (head(stamp, "%d phrasings of one task, before and after" % n)
            + """\\begin{tikzpicture}
\\begin{axis}[
    width=0.74\\linewidth, height=52mm,
    ybar, bar width=7pt, enlarge x limits=0.18,
    ymin=0, ymax=42,
    ylabel={utterances, of %d},
    ylabel style={font=\\scriptsize}, tick label style={font=\\scriptsize},
    xtick={0,1,2,3},
    xticklabels={correct, asked, refused, \\textbf{misunderstood}},
    xticklabel style={font=\\scriptsize},
    nodes near coords, nodes near coords style={font=\\tiny},
    legend style={font=\\scriptsize, at={(0.98,0.98)}, anchor=north east,
                  draw=none},
    axis lines*=left, grid=major, grid style={gray!18},
]
\\addplot[fill=black!15, draw=black!45] coordinates {%s};
\\addlegendentry{the earlier grammar}
\\addplot[fill=black!55, draw=black!70] coordinates {%s};
\\addlegendentry{as delivered}
\\node[font=\\tiny\\itshape, red!65!black, anchor=south, align=center]
  at (axis cs:3,6) {the only unsafe outcome:\\\\an arm that moves wrongly};
\\end{axis}
\\end{tikzpicture}
""" % (n, b, a))


# =================================================================== tasks
_ACC_RE = re.compile(r"^(\d\d_\w+)\s+(\d+)\s+([\d.]+)%\s+([\d.]+)\s+"
                     r"(--|[\d.]+)\s+(--|[\d.]+)\s+(\d+) mm\s*$", re.M)


def task_accuracy(camp, by, stamp):
    need(by, "tasks_accuracy")
    rows = _ACC_RE.findall(log_of(camp, "tasks_accuracy"))
    if not rows:
        raise Missing("the accuracy table did not parse")
    label = {"01_master_teleop": "01 mannequin teleoperation",
             "02_vr_teleop": "02 controller teleoperation",
             "03_shared_autonomy": "03 shared autonomy",
             "04_vr_shared": "04 controller, shared",
             "06_full_autonomy": "06 full autonomy"}
    body = []
    for mode, cells, grasp, pos, place, var, obj in rows:
        body.append("    %s & %s & \\SI{%s}{\\percent} & %s & %s & %s \\\\"
                    % (label.get(mode, _tex(mode)), cells, grasp, pos,
                       place if place != "--" else "---",
                       var if var != "--" else "---"))
    return (head(stamp, "the recorded clip set, scored")
            + "\\begin{tabular}{@{}lccccc@{}}\n"
              "  \\toprule\n"
              "  Mode & cells & grasp & positioning & placement & variance \\\\\n"
              "  & & success & \\si{\\milli\\metre} & \\si{\\milli\\metre}"
              " & \\si{\\milli\\metre} \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


# ---------------------------------------------- the task set, in the stack
_IK_RE = re.compile(r"(\d[\d\s]*)\s*IK calls[^\n]*?(?:TOTAL FAILURES:\s*(\d+)|,\s*(\d+) failures)")
_T1_WP = re.compile(r"waypoints\s+left (\d+), right (\d+), N=(\d+), floor ([\d.]+)")
_T1_FAIL = re.compile(r"^\s+(left|right)\s+(\d+) waypoints: (\d+) IK failures, (\d+) inside", re.M)
_T1_CLEAR = re.compile(r"worst clearance ([\d.]+) m")
_DANCE_RE = re.compile(r"^\s+(d\d)\s+dance: (\w+)\s+(\d+) of\s+(\d+) waypoints FAIL", re.M)


def _ikcalls(txt):
    m = re.search(r"([\d\s]+)IK calls", txt)
    if not m:
        raise Missing("no IK call count in the log")
    return int(m.group(1).replace(" ", ""))


def task_set(camp, by, stamp):
    """T1, the MSc set and the demonstration routines, in one table.

    Every row is IK success over a DENSIFIED path at N repeats, not a single
    call: TRAC-IK restarts randomly, so one call is one coin flip and a pose
    that passes once is not reachable.
    """
    for k in ("tasks_t1", "tasks_msc", "tasks_dance"):
        need(by, k)
    t1 = log_of(camp, "tasks_t1")
    msc = log_of(camp, "tasks_msc")
    dan = log_of(camp, "tasks_dance")

    wp = _T1_WP.search(t1)
    if not wp:
        raise Missing("T1's waypoint header did not parse")
    per = _T1_FAIL.findall(t1)
    if len(per) != 2:
        raise Missing("T1 did not report both arms")
    clear = min(float(c) for c in _T1_CLEAR.findall(t1)) if \
        _T1_CLEAR.findall(t1) else None
    dance = _DANCE_RE.findall(dan)
    if len(dance) != 3:
        raise Missing("the routines did not parse (%d rows)" % len(dance))

    n_t1, n_msc, n_dan = _ikcalls(t1), _ikcalls(msc), _ikcalls(dan)
    fails = (sum(int(p[2]) + int(p[3]) for p in per)
             + int(re.search(r"TOTAL FAILURES:\s*(\d+)", msc).group(1))
             + sum(int(d[2]) for d in dance))

    rows = []
    rows.append("    \\multicolumn{5}{@{}l}{\\itshape "
                "T1, both arms, pick and place by colour} \\\\")
    for arm, n, f, breach in per:
        rows.append("    \\quad %s arm & %s & %s & %s & %s \\\\"
                    % (arm, n, wp.group(3), f, breach))
    rows.append("    \\addlinespace[2pt]")
    rows.append("    \\multicolumn{5}{@{}l}{\\itshape "
                "the MSc task set} \\\\")
    for name, pat in (("T0 target reaching",
                       r"sampled: (\d+) poses, (\d+) unreachable"),):
        m = re.search(pat, msc)
        if m:
            rows.append("    \\quad %s & %s & 10 & %s & --- \\\\"
                        % (name, m.group(1), m.group(2)))
    for label, pat in (("T2 coordinated carry",
                        r"S1_short_lift\s+(\d+) waypoints, (\d+) failures"),
                       ("T3 circuit box",
                        r"circuit_box\s+right arm, (\d+) waypoints, (\d+) fail")):
        m = re.search(pat, msc)
        if m:
            rows.append("    \\quad %s & %s & 10 & %s & --- \\\\"
                        % (label, m.group(1), m.group(2)))
    m = re.search(r"(\d+) distinct clip waypoints tested at N=(\d+)", msc)
    if m:
        rows.append("    \\quad every recorded clip path & %s & %s & 0 & --- \\\\"
                    % (m.group(1), m.group(2)))
    rows.append("    \\addlinespace[2pt]")
    rows.append("    \\multicolumn{5}{@{}l}{\\itshape "
                "the demonstration routines} \\\\")
    for key, name, f, n in dance:
        rows.append("    \\quad %s (%s) & %s & 3 & %s & --- \\\\"
                    % (key, name, n, f))
    rows.append("    \\midrule")
    rows.append("    \\textbf{total} & \\multicolumn{2}{c}{\\textbf{%s IK calls}}"
                " & \\textbf{%d} & \\textbf{0} \\\\"
                % ("{:,}".format(n_t1 + n_msc + n_dan).replace(",", "\\,"),
                   fails))
    return (head(stamp, "the task set, inside the simulated platform")
            + "\\begin{tabular}{@{}lcccc@{}}\n"
              "  \\toprule\n"
              "  & waypoints & repeats & IK & floor \\\\\n"
              "  Path & densified & $N$ & failures & breaches \\\\\n"
              "  \\midrule\n"
            + "\n".join(rows)
            + "\n  \\bottomrule\n\\end{tabular}\n")


_MEAN_RE = re.compile(
    r"^\s+(pinned|spin|cone15|cone45|free)\s+([\d.]+) m\s+\((\d+) walks?", re.M)
_CTRL3_RE = re.compile(r"CONTROL 3 FAILED on (\d+) walk")
_ROLL_RE = re.compile(r"unpinning the ROLL alone is worth ([+\-]\d+) mm")


def orientation_convergence(camp, by, stamp):
    """The same sweep at every sampling density it was run at.

    Read from the LOGS of every campaign on disk rather than from the
    baseline file, because each run overwrites that file and the point of
    this table is the DIFFERENCE between runs. A single column would be a
    number; the set of columns is the finding.
    """
    runs = []
    for c in sorted(CAMPAIGNS):
        lg = os.path.join(c, "logs", "teleop_orientation_cost.log")
        cj = os.path.join(c, "campaign.json")
        if not (os.path.exists(lg) and os.path.exists(cj)):
            continue
        txt = open(lg).read()
        means = dict((k, (float(v), int(w))) for k, v, w in _MEAN_RE.findall(txt))
        if len(means) != 5:
            continue
        argv = " ".join(json.load(open(cj)).get("argv", []))
        st = [x for x in json.load(open(cj))["stages"]
              if x["key"] == "teleop_orientation_cost"]
        seeds = None
        for x in st:
            a = x.get("argv", [])
            if "--seeds" in a:
                seeds = int(a[a.index("--seeds") + 1])
        if seeds is None:
            continue
        bad = _CTRL3_RE.search(txt)
        roll = _ROLL_RE.search(txt)
        # WHICH VERSION OF THE CONTROL RAN. Two runs share a seed count and
        # differ only in whether capped walks are excluded from the
        # monotonicity test, so the seed count alone does not identify a
        # column. The corrected control announces its exclusions; the older
        # one had nothing to announce.
        fixed = "EXCLUDED because the tighter policy hit the search cap" in txt
        runs.append(dict(seeds=seeds, means=means, fixed=fixed,
                         skipped=len(re.findall(r"\(CAPPED\) vs", txt)),
                         bad=int(bad.group(1)) if bad else 0,
                         roll=int(roll.group(1)) if roll else None))
    if len(runs) < 2:
        raise Missing("fewer than two orientation sweeps on disk; the point "
                      "of this table is the difference between them")
    runs.sort(key=lambda r: (r["seeds"], r["fixed"]))
    label = [("pinned", "pinned to the anchor (delivered)"),
             ("spin", "roll free"),
             ("cone15", "\\SI{15}{\\degree} cone"),
             ("cone45", "\\SI{45}{\\degree} cone"),
             ("free", "position only")]
    cols = " & ".join(
        ("\\begin{tabular}{@{}c@{}}%d seeds\\\\\\scriptsize %s"
         "\\end{tabular}") % (r["seeds"],
                              "capped walks excluded" if r["fixed"]
                              else "all walks compared")
        for r in runs)
    body = []
    for key, nice in label:
        body.append("    %s & %s \\\\"
                    % (nice, " & ".join("\\num{%.3f}" % r["means"][key][0]
                                        for r in runs)))
    body.append("    \\midrule")
    body.append("    what the roll appears to buy & %s \\\\"
                % " & ".join(("$%+d$\\,mm" % r["roll"]) if r["roll"] is not None
                             else "---" for r in runs))
    body.append("    walks stopped by the wearer, of 28 & %s \\\\"
                % " & ".join(str(r["means"]["pinned"][1]) for r in runs))
    body.append("    a looser policy reached \\emph{less} far & %s \\\\"
                % " & ".join("\\textbf{%d}" % r["bad"] for r in runs))
    body.append("    excluded as capped lower bounds & %s \\\\"
                % " & ".join(("%d" % r["skipped"]) if r["fixed"] else "---"
                             for r in runs))
    return (head(stamp, "the orientation sweep at every sampling density")
            + "\\footnotesize\n\\begin{tabular}{@{}l%s@{}}\n" % ("c" * len(runs))
            + "  \\toprule\n"
              "  & \\multicolumn{%d}{c}{mean reach over 28 walks, \\si{\\metre}} \\\\\n"
              % len(runs)
            + "  \\cmidrule(l){2-%d}\n" % (len(runs) + 1)
            + "  Orientation policy & %s \\\\\n" % cols
            + "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


def _tex(s):
    for a, b in (("\\", "\\textbackslash "), ("_", "\\_"), ("%", "\\%"),
                 ("&", "\\&"), ("#", "\\#"), ("$", "\\$")):
        s = s.replace(a, b)
    return s


GROUP_LABEL = {
    "computer vision": "computer vision",
    "teleoperation": "teleoperation",
    "robot tasks": "robot tasks",
    "autonomy": "autonomy",
    "study": "study design",
    "transfer": "transfer to hardware",
}
TIER_LABEL = {"standalone": "standalone", "stack": "simulated platform",
              "recorded": "recorded data"}
STATUS_LABEL = {"ok": "\\checkmark", "failed": "\\textbf{failed}",
                "skipped": "\\textit{not run}",
                "missing": "\\textbf{missing}"}


def _secs(v):
    """Durations that read as a duration. A sub-second stage shown as
    `0 s` reads like a stage that did not run, which is the one thing this
    column must never be confusable with."""
    if v is None:
        return "---"
    if v < 1:
        return "$<\\SI{1}{\\second}$"
    if v < 100:
        return "\\SI{%.0f}{\\second}" % v
    return "\\SI{%.1f}{\\minute}" % (v / 60.0)


def campaign_inventory(camp, by, stamp):
    """Every stage, its tier and its outcome. The whole campaign on one page.

    Ordered by group and then by key so a re-run produces the same table, and
    NOT by duration, which would reorder the rows on every machine.
    """
    if not by:
        raise Missing("the campaign has no stages")
    order = ["computer vision", "teleoperation", "robot tasks", "autonomy",
             "study", "transfer"]
    rows = sorted(by.values(),
                  key=lambda s: (order.index(s["group"])
                                 if s.get("group") in order else 99,
                                 s["key"]))
    body, seen = [], None
    for r in rows:
        g = GROUP_LABEL.get(r.get("group"), r.get("group", "?"))
        if g != seen:
            if seen is not None:
                body.append("    \\addlinespace[2pt]")
            body.append("    \\multicolumn{4}{@{}l}{\\itshape %s} \\\\" % g)
            seen = g
        secs = r.get("seconds")
        body.append("    \\quad \\repo{%s} & %s & %s & %s \\\\"
                    % (r["key"].replace("_", "\\_"),
                       TIER_LABEL.get(r.get("tier"), r.get("tier", "?")),
                       STATUS_LABEL.get(r.get("status"), r.get("status", "?")),
                       _secs(secs)))
    return (head(stamp, "the campaign, stage by stage")
            + "\\begin{tabular}{@{}llcr@{}}\n"
              "  \\toprule\n"
              "  Stage & Needs & Ran & Time \\\\\n"
              "  \\midrule\n"
            + "\n".join(body)
            + "\n  \\bottomrule\n\\end{tabular}\n")


FIGURES = [
    ("sim_campaign_inventory.tex", campaign_inventory),
    ("sim_cv_selftest.tex", cv_selftest),
    ("sim_teleop_generators.tex", teleop_generators),
    ("sim_teleop_stepsweep.tex", teleop_stepsweep),
    ("sim_teleop_smoothing.tex", teleop_smoothing),
    ("sim_teleop_replay.tex", teleop_replay),
    ("sim_autonomy_sweep.tex", autonomy_sweep),
    ("sim_autonomy_instructions.tex", autonomy_instructions),
    ("sim_task_accuracy.tex", task_accuracy),
    ("sim_task_set.tex", task_set),
    ("sim_orientation_convergence.tex", orientation_convergence),
]


def self_test():
    """The generators must REFUSE on a campaign that produced nothing."""
    import tempfile
    ok = fail = 0

    def check(name, cond):
        nonlocal ok, fail
        if cond:
            ok += 1
            print("  ok    %s" % name)
        else:
            fail += 1
            print("  FAIL  %s" % name)

    with tempfile.TemporaryDirectory() as d:
        empty = dict(stamp="none", stages=[])
        with open(os.path.join(d, "campaign.json"), "w") as fh:
            json.dump(empty, fh)
        CAMPAIGNS[:] = [d]
        by, _homes, _st = load_many([d])
        refused = 0
        for _n, fn in FIGURES:
            try:
                fn(d, by, "none")
            except Missing:
                refused += 1
            except Exception as exc:                         # noqa: BLE001
                print("     (%s raised %s instead of refusing)"
                      % (fn.__name__, type(exc).__name__))
        check("every figure refuses an empty campaign (%d/%d)"
              % (refused, len(FIGURES)), refused == len(FIGURES))

        # A stage that FAILED must also refuse, not be treated as absent-ok.
        with open(os.path.join(d, "campaign.json"), "w") as fh:
            json.dump(dict(stamp="x", stages=[
                dict(key="teleop_motion", status="failed")]), fh)
        by, _homes, _st = load_many([d])
        try:
            teleop_generators(d, by, "x")
            check("a FAILED stage is refused", False)
        except Missing:
            check("a FAILED stage is refused", True)
    print("\n%d checks, %d failed" % (ok + fail, fail))
    return 1 if fail else 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--campaign", default="", nargs="*",
                    help="one or more campaign directories, merged in order; "
                         "a later one wins on a key it shares")
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return self_test()

    camps = list(a.campaign) if a.campaign else [newest_campaign()]
    CAMPAIGNS[:] = camps
    by, camp, stamp = load_many(camps)
    os.makedirs(a.out, exist_ok=True)
    print("campaign %s" % stamp)
    made = refused = 0
    for name, fn in FIGURES:
        try:
            body = fn(camp, by, stamp)
        except Missing as exc:
            print("  REFUSED  %-34s %s" % (name, exc))
            refused += 1
            continue
        with open(os.path.join(a.out, name), "w") as fh:
            fh.write(body)
        print("  wrote    %-34s %d bytes" % (name, len(body)))
        made += 1
    with open(os.path.join(a.out, "PROVENANCE.md"), "w") as fh:
        fh.write("Generated by `scripts/make_sim_figures.py` from:\n\n"
                 + "".join("* `%s`\n" % os.path.relpath(c, WS) for c in camps)
                 + "\n%d written, %d refused.\n" % (made, refused))
    print("\n%d written, %d refused -> %s"
          % (made, refused, os.path.relpath(a.out, WS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
