#!/usr/bin/env python3
"""Build recordings/verification/INDEX.md from what is ACTUALLY on disk.

GENERATED, NEVER HAND-WRITTEN. A hand-written index goes stale the first time
a sweep runs and then quietly misdescribes the clips -- this file was
previously overwritten by a script that dropped 38 of them and discarded a
caveat with them. Everything below is read from the clips, the sweep progress
file and the verifier's own output, so the index cannot claim a clip that is
not there or a pass that was not measured.
"""
import json
import os
import subprocess
import sys

WS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(WS, "recordings/verification")
FFMPEG = os.environ.get("FFMPEG") or os.path.expanduser("~/.local/bin/ffmpeg")
sys.path.insert(0, os.path.join(WS, "src/srl_experiments/experiments/abc"))

ANGLES = ("front", "back", "left", "right", "iso", "gripper", "quad")

MODE_NOTE = {
    "01_master_teleop": "scripted master input on /master_arm_pose_<arm>",
    "02_vr_teleop": "scripted Quest input through vr_pose_mapper",
    "03_shared_autonomy": "autonomy commanding on /autonomy/assist_pose_<arm>",
    "04_vr_shared": "VR transport up AND autonomy owning the pose",
    "06_full_autonomy": "no operator input at all",
}


def dur(mp4):
    try:
        r = subprocess.run([FFMPEG, "-i", mp4], capture_output=True, text=True)
        import re
        m = re.search(r"Duration:\s*(\d+):(\d+):(\d+\.\d+)", r.stderr or "")
        if m:
            return int(m.group(2)) * 60 + float(m.group(3))
    except Exception:                                         # noqa: BLE001
        pass
    return 0.0


def main():
    prog = {}
    try:
        prog = json.load(open(os.path.join(OUT, "abc_sweep_progress.json")))
    except Exception:                                         # noqa: BLE001
        pass
    vfy = {}
    try:
        for r in json.load(open(os.path.join(OUT, "rviz_verification.json"))):
            vfy[(r.get("mode"), r.get("task"), r.get("scenario"))] = r
    except Exception:                                         # noqa: BLE001
        pass
    try:
        import clip_tasks as CT
        TASKS = CT.TASKS
    except Exception:                                         # noqa: BLE001
        TASKS = {}

    rows = []
    for mode in sorted(MODE_NOTE):
        md = os.path.join(OUT, mode)
        if not os.path.isdir(md):
            continue
        for task in sorted(os.listdir(md)):
            td = os.path.join(md, task)
            if not os.path.isdir(td):
                continue
            for scen in sorted(os.listdir(td)):
                d = os.path.join(td, scen)
                front = os.path.join(d, "rviz_front.mp4")
                if not os.path.exists(front):
                    continue
                have = [a for a in ANGLES
                        if os.path.exists(os.path.join(d, "rviz_%s.mp4" % a))]
                key = "%s/%s/%s" % (mode, task.lower(), scen)
                v = vfy.get((mode, task.lower(), scen)) or {}
                rows.append(dict(
                    mode=mode, task=task.lower(), scen=scen,
                    rel=os.path.relpath(d, WS), angles=len(have),
                    missing=[a for a in ANGLES if a not in have],
                    dur=dur(front),
                    recorded=prog.get(key, {}).get("ok"),
                    verified=v.get("ok"),
                    why=v.get("why", ""),
                    spec=TASKS.get(task.lower(), {})))

    lang = os.path.join(OUT, "06_full_autonomy/LANGUAGE/language_sweep.mp4")
    lang_counts = {}
    try:
        lang_counts = json.load(open(
            os.path.join(OUT, "06_full_autonomy/LANGUAGE/language_sweep.json"))
        )["counts"]
    except Exception:                                         # noqa: BLE001
        pass

    L = []
    A = L.append
    A("# Verification clips")
    A("")
    A("Generated by `scripts/make_clip_index.py` from what is on disk, the "
      "sweep progress file and the verifier's own output. Do not hand-edit: "
      "it is rewritten on every run.")
    A("")
    A("## Open these five first")
    A("")
    A("| # | what it shows | file |")
    A("| --- | --- | --- |")
    # ==================================================================
    # THE SHORTLIST IS RESOLVED AGAINST DISK, AND IT USED NOT TO BE
    # ==================================================================
    # These five paths were written out by hand, against the A/B/C task set
    # that was retired when the MSc tasks replaced it. Four of the five named
    # files -- `06_full_autonomy/B/S1_bimanual`, `01_master_teleop/A/
    # S1_single_arm`, `02_vr_teleop/B/S1_bimanual`, `06_full_autonomy/A/
    # S1_single_arm` -- have not existed for weeks, in the one section of the
    # one document whose entire job is to say WHICH FILE TO OPEN FIRST.
    #
    # This file's own header says it is generated so that it "cannot claim a
    # clip that is not there". That was true of the table below and false of
    # the shortlist above it.
    #
    # So each entry is a PREFERENCE ORDER now, and the first one that is
    # actually on disk wins. An entry whose candidates are all missing says so
    # in place, rather than printing a path that 404s in Explorer.
    def _first_on_disk(*rels):
        for r in rels:
            if os.path.exists(os.path.join(WS, r)):
                return "`%s`" % r
        return "**not on disk** -- run `bash scripts/record_everything.sh`"

    V = "recordings/verification"
    top = [
        ("The language sweep -- 40 phrasings, every outcome captioned. "
         "%s. The most complete evidence in the set, and the only mode that "
         "needs no operator."
         % (", ".join("%s %d" % (k, v) for k, v in sorted(lang_counts.items()))
            or "see the video"),
         "`%s`" % os.path.relpath(lang, WS) if os.path.exists(lang)
         else "**not built** -- run `scripts/record_language_sweep.py`"),
        ("**Full autonomy picking and placing four cubes by colour, from a "
         "typed sentence** -- four views tiled. The task the rest of the set "
         "exists to support.",
         _first_on_disk(V + "/06_full_autonomy/T1/S1_both_arms_centre/rviz_quad.mp4")),
        ("The same task with the layout drawn from a seed, both arms at once.",
         _first_on_disk(V + "/06_full_autonomy/T1S2/S2_both_arms_random/rviz_quad.mp4")),
        ("Master teleop reaching three targets -- the baseline condition every "
         "other mode is compared against.",
         _first_on_disk(V + "/01_master_teleop/T0/D3_three_targets/rviz_front.mp4")),
        ("**The gripper view**: tight on the fingers through a pick. This is "
         "where a grasp is judged rather than asserted.",
         _first_on_disk(V + "/06_full_autonomy/T1/S1_both_arms_centre/rviz_gripper.mp4")),
    ]
    for i, (what, f) in enumerate(top, 1):
        A("| %d | %s | %s |" % (i, what, f))
    A("")

    A("## Opening them from Windows")
    A("")
    A("The repository lives inside WSL. From Windows, either:")
    A("")
    A("```")
    A(r"\\wsl$\Ubuntu\home\gausms\kortex_ws\recordings\verification\...")
    A("```")
    A("")
    A("paste that into Explorer's address bar, or from a WSL shell run "
      "`explorer.exe .` inside the clip's folder, which opens it in Explorer "
      "at that location. Every file is H.264 in an MP4 and plays in the "
      "Windows media player without anything installed.")
    A("")

    A("## Every clip")
    A("")
    A("`recorded` is the runner's own verdict -- it exits non-zero if no arm "
      "moved. `verified` is the pixel check: not black, real colour variety, "
      "actual motion between frames, and any required object visible.")
    A("")
    A("| mode | task | scenario | angles | s | recorded | verified |")
    A("| --- | --- | --- | --- | --- | --- | --- |")
    for r in rows:
        A("| %s | %s | %s | %d/7%s | %.0f | %s | %s |"
          % (r["mode"], r["task"].upper(), r["scen"], r["angles"],
             "" if not r["missing"] else " (missing %s)" % ",".join(r["missing"]),
             r["dur"],
             "yes" if r["recorded"] else ("--" if r["recorded"] is None
                                          else "**NO**"),
             "yes" if r["verified"] else ("--" if r["verified"] is None
                                          else "**NO** " + r["why"][:40])))
    A("")

    A("## What each task should show")
    A("")
    for k in ("a", "b", "c"):
        s = TASKS.get(k)
        if not s:
            continue
        A("**Task %s -- %s** (`%s`)" % (k.upper(), s["name"], s["scenario"]))
        A("")
        A("- expected: %s" % s["expect"])
        if s["caveat"]:
            A("- **caveat: %s**" % s["caveat"])
        A("")

    A("## Read this before drawing conclusions")
    A("")
    A("- **The clips DO carry task objects, and the grasp is real.** The "
      "sweep starts `scripts/clip_scene.py` per task, which publishes the "
      "bench, the bin and one graspable object, and ATTACHES that object to "
      "the gripper only once the fingers actually reach the object's width "
      "(`knuckle >= 0.90 * grip_for(width_mm)`) -- not merely once the "
      "gripper enters a holding band, which would snap the object to the "
      "hand while the fingers were still visibly open. Release leaves the "
      "object where it was put rather than snapping it back, so a successful "
      "place and a failed one do not look alike. Each clip's "
      "`scene_events.json` records the GRASPED and RELEASED times, the "
      "knuckle angle against the angle required, and how far the object "
      "travelled WHILE HELD.")
    A("- **Capture starts on first arm motion, not at launch.** Measured on "
      "the clips this replaced: a 28.4 s recording whose arm moved only "
      "during seconds 16-26, so 56% of the file was node startup and DDS "
      "discovery with nothing changing on screen, and 82% of frame pairs "
      "were bit-identical. Gating the grab on `/joint_states` leaving its "
      "reference took the same task and mode from 28.4 s to 11.3 s and the "
      "delivered rate from 1.29 to 5.41 fps. If motion is never detected the "
      "grab starts anyway after 45 s, so a mode that FAILS to move is still "
      "recorded and can be seen to have failed.")
    A("- **The frame rate in the container is not the delivered rate.** "
      "x11grab writes its requested rate whatever the source managed, "
      "duplicating pixels when RViz has not repainted. Requested is 15 fps, "
      "set just under a measured 16.0 fps render ceiling "
      "(`scripts/measure_render_rate.py`; the WSL d3d12 GPU path gives 16.3, "
      "so the GL driver is not the limit). Judge a clip by frames that "
      "CHANGE, never by the header.")
    A("- **Task C is the present-and-probe motion, not a multimeter.** There "
      "is no multimeter model in this repository. The caveat is burnt into "
      "every C clip's caption.")
    A("- **One mode owned the graph at a time.** The sweep tears down the "
      "previous mode's publishers and counts publishers on the follower's "
      "input topic against a number predicted in advance, refusing to record "
      "if they disagree. Without it every mode after the first records a "
      "stationary arm and the set looks plausible and is worthless.")
    A("- **The captions are on the FRONT view and the quad only.** The other "
      "five angles are deliberately clean.")
    A("- Clips under `00_unclassified_*` predate this sweep, were produced by "
      "a recorder that called `/compute_ik` directly with no control mode in "
      "the path, and use retired geometry. They are kept for reference and "
      "prove nothing about the current task set.")
    A("")

    p = os.path.join(OUT, "INDEX.md")
    open(p, "w").write("\n".join(L) + "\n")
    nv = sum(1 for r in rows if r["verified"])
    print("%d clips indexed, %d verified -> %s" % (len(rows), nv, p))
    return 0


if __name__ == "__main__":
    sys.exit(main())
